#ifndef OSMOSIS_SYSCALL_NUMBERS_H
#define OSMOSIS_SYSCALL_NUMBERS_H

#define OSMOSIS_SYS_WRITE   0
#define OSMOSIS_SYS_EXIT    1
#define OSMOSIS_SYS_GETPID  2
#define OSMOSIS_SYS_BRK     3
#define OSMOSIS_SYS_FORK    4
#define OSMOSIS_SYS_EXECVE  5
#define OSMOSIS_SYS_WAITPID 6

#endif
